Minor update to check_and_set_allowance() in check_allowance.py
Resolve error [ERROR] Error: 'SignedTransaction' object has no attribute 'rawTransaction'